DROP TABLE MEMBERS;
CREATE TABLE MEMBERS(
    MEM_NAME VARCHAR(20) NOT NULL,
    PHONE_NUM VARCHAR(20) CONSTRAINT MEMBERS_PHONE_NUM_PK UNIQUE,
    EMAIL VARCHAR2(80) CONSTRAINT MEMBERS_EMAIL_PK UNIQUE,
    ID VARCHAR(30) CONSTRAINT MEMBERS_ID_PK PRIMARY KEY,
    PW VARCHAR(30) NOT NULL,
    SIGNED_DATE DATE,
    CARD_ID VARCHAR(20) CONSTRAINT MEMBERS_CARD_ID_PK UNIQUE,
    CREDIT NUMBER
);

CREATE TABLE BOARD(
    BOARD_ID VARCHAR2(10) CONSTRAINT BOARD_PK PRIMARY KEY NOT NULL,
    BOARD_NM VARCHAR2(50) NOT NULL,
    USE_YN VARCHAR2(1) NOT NULL,
    REG_DATE DATE NOT NULL,
    BOARD_DESC VARCHAR2(100) NULL
);

INSERT INTO BOARD VALUES(1, 'Q&A', 'Y', SYSDATE, 'Q&A 게시판');

SELECT * FROM BOARD;

SELECT TRANSLATE('ABBA', 'A', 'abc') FROM DUAL;

INSERT INTO MEMBERS(MEM_NAME, PHONE_NUM, EMAIL, ID, PW, SIGNED_DATE, CARD_ID, CREDIT)
VALUES('jaehwan', '010-4590-9812', '1nth2bleakmidwinter@gmail.com', 'bleakwinter', 'bleakwinter', SYSDATE, '9490-9495-3668-4042', 10000);

INSERT INTO MEMBERS(MEM_NAME, PHONE_NUM, EMAIL, ID, PW, SIGNED_DATE, CARD_ID, CREDIT)
VALUES('broker', '--', '--', 'broker', 'broker', SYSDATE, '---', 10000000)

CREATE TABLE DIBS(
    MEM_ID VARCHAR(30),
    DIA_ID NUMBER
);

CREATE OR REPLACE TRIGGER DIBS_TRG
BEFORE DELETE ON STORE_ FOR EACH ROW
BEGIN
    DELETE FROM DIBS WHERE DIA_ID=:OLD.DIA_ID;
END;

SELECT * FROM MEMBERS;
SELECT * FROM STORE_;
SELECT * FROM DIBS;
SELECT * FROM STORE_ S JOIN (SELECT DIA_ID FROM DIBS WHERE MEM_ID='bleakwinter') X USING(DIA_ID)
SELECT COUNT(DIA_ID) FROM STORE_ S JOIN (SELECT DIA_ID FROM DIBS WHERE MEM_ID='bleakwinter') X USING(DIA_ID)
SELECT * FROM (SELECT ROWNUM RN, S.* FROM (SELECT * FROM STORE_ JOIN (SELECT DIA_ID FROM DIBS WHERE MEM_ID='bleakwinter') X USING(DIA_ID)) S ) WHERE 1<=RN AND RN<=7

INSERT INTO DIBS(MEM_ID, DIA_ID) VALUES('bleakwinter', 27680);

INSERT INTO STORE_ VALUES(66666, 5, 'Ideal', 'G', 'VS1', 66, 60, 8.5, 8.1, 7, 1000, 'bleakwinter')

SELECT * FROM DIBS WHERE MEM_ID='bleakwinter' AND DIA_ID=0
DELETE FROM DIBS WHERE MEM_ID='bleakwinter' AND DIA_ID=27680

DELETE FROM MEMBERS WHERE ID='bleakwinter';
SELECT * FROM MEMBERS WHERE ID='bleakwinter';

SELECT * FROM DIAMONDS ORDER BY PRICE DESC;
SELECT COUNT(DIA_ID) FROM DIAMONDS;

SELECT * FROM (SELECT ROWNUM RN, D.* FROM (SELECT * FROM DIAMONDS) D ) WHERE 1<=RN AND RN<=125;

CREATE TABLE STORE_ AS SELECT * FROM (SELECT ROWNUM RN, D.* FROM (SELECT * FROM DIAMONDS) D ) WHERE RN<=125 ORDER BY PRICE DESC;

SELECT * FROM STORE_;
SELECT * FROM (SELECT ROWNUM RN, S.* FROM (SELECT * FROM STORE_ WHERE OWNER='broker' ORDER BY PRICE DESC) S ) WHERE 1<=RN AND RN<=7;
SELECT * FROM (SELECT ROWNUM RN, S.* FROM (SELECT * FROM STORE_ WHERE OWNER='broker' ORDER BY PRICE DESC) S )


UPDATE MEMBERS SET CREDIT=20000


-- DROP TABLE STORE_;
-- ALTER TABLE STORE_ DROP COLUMN RN;
-- SELECT COUNT(DIA_ID) FROM STORE_

ALTER TABLE STORE_ ADD OWNER VARCHAR(30) DEFAULT 'broker' NOT NULL;

SELECT * FROM STORE_ WHERE COLOR='D' AND CARAT>1.1 ORDER BY PRICE DESC;

SELECT COUNT(DIA_ID) FROM (SELECT ROWNUM RN, S.* FROM (SELECT * FROM STORE_ WHERE PRICE<=1000 ORDER BY PRICE DESC) S)